#!/usr/bin/env python3
"""Validate lessons.tsv against roots.tsv, compounds.tsv, and corpus.tsv.

    python3 check_lessons.py     the table, and any problems

The lesson plan is the one hand-authored piece of the course: per lesson, a
page to read and a list of new items.  Everything else -- the review cards,
the sentence cards, the level review lists -- is generated by gen_lessons.py,
so this script's job is to prove the authored part is consistent:

  * every item reference resolves to a root gloss or a compound gloss
  * no item is introduced twice
  * a level's items are exactly the roots at that `Level` plus the compounds
    at that `assigned_level` -- nothing missing, nothing borrowed from later
  * every compound's constituent roots are introduced no later than the
    compound itself
  * every page a lesson links to is one that exists

The walk over the plan is gen_lessons.Course.walk(), not a second copy of it:
what a learner knows by lesson N decides both what may be validated and what
may be put on a card, and those two must not be able to disagree.

It also reports two counts per lesson.  `pool` is every corpus sentence
readable by then and `fresh` is the ones that lesson unlocked; sentence cards
come from the pool but lead with the fresh ones, so a lesson whose `fresh` is
0 is one whose new words the corpus has never put in a sentence.  That is
allowed -- three lessons in Levels 1-3 are like that, and a deck with no
sentences in it is simply a short one.
"""

import sys

import gen_lessons


def validate(states=None, course=None, report=None):
    """Every problem with the plan, as a list of lines; empty when it is sound.

    build.py fails on anything this returns.  `report` collects the per-lesson
    counts for the caller that wants to print them."""
    course = course or gen_lessons.Course()
    states = states if states is not None else list(course.walk())

    problems = []
    seen_items = set()
    known_roots = set()
    per_level = {}

    pages = _page_urls()

    for state in states:
        row = state["row"]
        tag = state["id"]

        if row["page"] and row["page"] not in pages:
            problems.append(f"{tag}: {row['page']} is not a page on the site")

        for item in state["items"]:
            if item in seen_items:
                problems.append(f"{tag}: {item!r} is introduced twice")
            seen_items.add(item)

            if item in course.compound:
                need = course.roots_of(item)
                if need is None:
                    problems.append(f"{tag}: {item!r} cannot be read as a compound")
                    continue
                # The compound's own roots count as taught by the end of the
                # lesson that teaches it, so a lesson may introduce both at once.
                same_lesson = set()
                for other in state["items"]:
                    if other in course.alias:
                        same_lesson.add(course.alias[other])
                missing = need - known_roots - same_lesson
                if missing:
                    problems.append(
                        f"{tag}: compound {item!r} needs roots not yet taught: "
                        + ", ".join(sorted(missing)))
                known_roots |= need
                # Under the row's own gloss, not the spelling the lesson used:
                # a compound may be named by either keyword of any of its roots,
                # and the budget below is counted against compounds.tsv.
                per_level.setdefault(row["level"], set()).add(
                    course.compound[item]["gloss"])
            elif item in course.alias:
                known_roots.add(course.alias[item])
                per_level.setdefault(row["level"], set()).add(course.alias[item])
            else:
                problems.append(f"{tag}: {item!r} is neither a root nor a compound")

        for line in course.corpus:
            if course.sentence_roots(line) is None:
                problems.append(f"corpus line {line['EN']!r} has an unreadable gloss")
                break

        if report is not None:
            report.append((tag, row["title"], row["page"] or "--",
                           len(state["items"]), len(state["readable"]),
                           len(state["fresh"])))

    # A level's budget has to be spent exactly: a root assigned to Level 2 and
    # taught nowhere is a word the course never gets to, and one taught in a
    # level it was not assigned to means the two tables disagree about when it
    # is due.
    for level, planned in sorted(per_level.items()):
        want = {r["gloss"] for r in course.roots if r["Level"] == level}
        want |= {c["gloss"] for c in course.compounds
                 if c["assigned_level"] == level}
        for gloss in sorted(want - planned):
            problems.append(f"level {level}: {gloss!r} is assigned to this "
                            "level but no lesson teaches it")
        for gloss in sorted(planned - want):
            problems.append(f"level {level}: {gloss!r} is taught here but "
                            "assigned elsewhere")

    return problems


def _page_urls():
    """Every grammar and topic page a lesson may send a learner to.

    Read out of build.py, which is where the sections are defined, so a
    lesson pointing at a page that was renamed or never written fails here
    rather than shipping as a dead link."""
    import build

    return set(build.page_titles())


def main():
    course = gen_lessons.Course()
    states = list(course.walk())
    report = []
    problems = validate(states, course, report)

    print("%-6s %-24s %-28s %5s %5s %5s"
          % ("", "title", "page", "new", "pool", "fresh"))
    for tag, title, page, new, pool, fresh in report:
        print("%-6s %-24s %-28s %5s %5s %5s"
              % (tag, title, page, new or "", pool, fresh))

    if problems:
        print("\n%d problem(s):" % len(problems))
        for line in problems:
            print("  " + line)
        return 1
    print("\nlessons.tsv is consistent with the tables.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
